# Generated by Django 3.2.5 on 2021-08-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, default='Null', max_length=25, verbose_name='адрес'),
        ),
    ]
